### ISSUE TITLE
Missing booster notification rules

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/dcc-rule-translation#4]
There is more than one booster notification rule, see https://timokoenig.github.io/eu-dcc-rules/?ruleset=de-bn-rules&country=DE&rule=BNR-DE-0100. 

Will these rules be added soon?

**Comment by BrittaTSI** [comment]
Hi @Ein-Tim - first of all the six active booster notification rules shown here https://timokoenig.github.io/eu-dcc-rules/?ruleset=de-bn-rules&country=DE are active and currently in use. 

You can see the differences in notifications for the different target groups in the descriptions in the right column. 
Boosters are recommended for the following cases:
- BNR-DE-100/110 - RKI recommendation for all people over 70 that have completed their two-shot basic vaccination cycle (100: > 6 months ago, 110: 5-6 months ago) and not received a booster shot yet. 
- BNR 200/210 - RKI recommendation for all people that have received the Janssen vaccine and no second shot yet. (200: 14-28 days since vaccination, 210: >28 days since vaccination)
- BNR 300 - BMG recommendation for all people who have completed their basic vaccination cycle > 6 months ago

BNR 1000 is not really a booster notification but uses the same mechanism to push informations into the CWA. It informs users who have received their vaccination certificate from a certain pharmacy that had issued compromised certificates that they have to get a new one.

Outlook - As you know, the recommendations of RKI/BMG have changed with regards to time frames and age groups since we had first defined these rules. So for BNR 100/110/200/210 there are updates planned that will probably be released in synch with CWA R2.21.
I hope this helps. :-)

**Comment by Ein-Tim** [comment]
Hey @BrittaTSI,

thanks for your long & detailed response! 

While it was very interesting to read, it did not really address the issue I tried to point out here.

When you take a look at https://github.com/corona-warn-app/dcc-rule-translation/blob/main/i18n/de/strings.xml you will only find **one** rule, although, as you say, there are actually six rules.

My question now was whether the other rules will soon be added to this repository?

> Outlook - As you know, the recommendations of RKI/BMG have changed with regards to time frames and age groups since we had first defined these rules. So for BNR 100/110/200/210 there are updates planned that will probably be released in synch with CWA R2.21.

That is so nice to hear, thank you!

**Comment by BrittaTSI** [comment]
Hi @Ein-Tim - now I get your question. Sorry for the confusion. ;-)

When we started defining the BNRs last year we only provided them in German and English due to our tight time schedule. The translations as well as the rules themselves were done by Telekom's language service.

For the updates and potential new rules we have agreed to provide them in all "CWA languages", i.e. additionally in Bulgarian, Romanian, Polish and Turkish. The translations will be done by SAP's translation service that also handles the translations of the other CWA-related texts to keep the wording consistent.

That of course means that we need a place to store the translations that is easily accessible by both SAP and DTAG. DTAG will receive the German version from RKI, deposit it here, SAP will fetch the texts, have them translated and store them in the folders for the different languages so DTAG can add them to the JSONs of the rules.

Right now there is no real content here yet. (The entry for BNR-DE-300 is just a dummy.) We will start filling the repo with the texts as soon as the specifications for the rules have been finalized by RKI/BMG.

I hope **this** helps. :-)

**Comment by Ein-Tim** [comment]
> Sorry for the confusion. ;-)

No problem at all, you gave me some other in-depth looks which I find to be quite interesting!

> We will start filling the repo with the texts as soon as the specifications for the rules have been finalized by RKI/BMG.

This was the answer I was searching & hoping for! Thanks.

Closing this issue as resolved.
